//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webOtt.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class search_history
    {
        public int ID { get; set; }
        public int USER_ID { get; set; }
        public string SEARCH_TERM { get; set; }
        public string SEARCH_KEY { get; set; }
        public bool IS_ENABLE { get; set; }
        public bool IS_DELETE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
    }
}
