//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webOtt.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public Nullable<int> ROLE { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN { get; set; }
        public bool IS_ENABLE { get; set; }
        public bool IS_DELETE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
    }
}
